# Generated by Django 2.2 on 2019-05-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagmar_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user1',
            new_name='participants',
        ),
        migrations.RenameField(
            model_name='massage',
            old_name='receiver',
            new_name='sender',
        ),
    ]
